"""Radiology Report Evaluator — LLM-as-Judge

Evaluates synthetic radiology reports (generated by GPT-o3 120B)
using a different model (DeepSeek R1 70B via Ollama) to avoid self-evaluation bias.

5 evaluation criteria:
  1. Clinical Accuracy   — Do findings match the ground truth disease?
  2. No Diagnosis Leakage — Does the report avoid naming the diagnosis?
  3. Completeness        — Are expected findings for this disease present?
  4. Internal Consistency — Do findings align with provided labs/vitals?
  5. Report Quality      — Structure, terminology, realism

Usage:
    python3 pipeline/evaluate_radiology_reports.py
    python3 pipeline/evaluate_radiology_reports.py --file data/gold/radiology_reports/all_reports.json
    python3 pipeline/evaluate_radiology_reports.py --limit 3
    python3 pipeline/evaluate_radiology_reports.py --model deepseek-r1:70b
"""

import argparse
import json
import re
import time
from datetime import datetime
from pathlib import Path

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "deepseek-r1:70b"
REPORTS_DIR = Path("data/gold/radiology_reports")
OUTPUT_DIR = Path("data/gold/radiology_evaluations")

EVALUATION_PROMPT = """You are a senior radiologist and clinical AI evaluator. Your task is to evaluate a synthetic radiology report that was generated by an AI model.

The report was generated for a patient with a KNOWN disease (ground truth). The goal of the report is to describe imaging findings CONSISTENT with the disease WITHOUT explicitly naming the diagnosis.

## Ground Truth
- **Disease**: {ground_truth_disease}
- **Modality**: {modality} of {body_site}
- **Patient**: {age}-year-old {gender}
- **Active conditions at time of scan**: {conditions}
- **Observations from same encounter**: {observations_count} lab/vital values available

## Report to Evaluate
```
{report_text}
```

## Evaluation Criteria

Score each criterion from 1-5 and provide a brief justification.

1. **Clinical Accuracy (1-5)**: Are the described findings realistic and consistent with the ground truth disease ({ground_truth_disease})? Would a patient with this condition plausibly show these findings on this imaging modality?

2. **No Diagnosis Leakage (1-5)**: Does the report successfully AVOID naming the diagnosis? Score 5 if the diagnosis is never mentioned. Score 1 if the disease name appears explicitly. Score 3 if the report uses near-synonyms or makes it too obvious.

3. **Completeness (1-5)**: Are the key/expected findings for this disease present? For example, if evaluating a chest X-ray for a cardiac condition, does it mention cardiac silhouette size, pulmonary vasculature, pleural effusions? Missing critical expected findings lower the score.

4. **Internal Consistency (1-5)**: Are the findings internally consistent? Do measurements make anatomical sense? Are there contradictions within the report? If lab values were referenced, are they used correctly?

5. **Report Quality (1-5)**: Does the report follow standard radiology report structure (Technique, Findings, Impression)? Is the terminology appropriate? Would this pass as a real radiology report?

## Response Format

Return ONLY valid JSON with this exact structure (no other text before or after):
{{
  "clinical_accuracy": {{"score": <1-5>, "justification": "<brief reason>"}},
  "no_diagnosis_leakage": {{"score": <1-5>, "justification": "<brief reason>", "leaked_terms": ["<any disease-naming terms found, or empty list>"]}},
  "completeness": {{"score": <1-5>, "justification": "<brief reason>", "missing_findings": ["<expected findings not present, or empty list>"]}},
  "internal_consistency": {{"score": <1-5>, "justification": "<brief reason>"}},
  "report_quality": {{"score": <1-5>, "justification": "<brief reason>"}},
  "overall_score": <average of all 5 scores, rounded to 1 decimal>,
  "summary": "<2-3 sentence overall assessment>",
  "could_agent_diagnose": "<yes/no/partially — could a clinical AI agent reasonably infer the correct diagnosis from this report alone?>"
}}"""


def load_reports(reports_path, limit=None):
    """Load reports from the combined JSON file."""
    data = json.loads(reports_path.read_text())
    if limit:
        data = data[:limit]
    return data


def build_eval_prompt(report):
    """Build the evaluation prompt for one report."""
    meta = report["generation_metadata"]
    age = "unknown"
    gender = "unknown"

    conditions = meta.get("active_conditions", [])
    conditions_text = ", ".join(conditions) if conditions else "None documented"

    return EVALUATION_PROMPT.format(
        ground_truth_disease=meta["ground_truth_disease"],
        modality=report["modality"],
        body_site=report["body_site"],
        age=age,
        gender=gender,
        conditions=conditions_text,
        observations_count=meta.get("observations_used", 0),
        report_text=report["report"],
    )


def call_ollama(prompt, model):
    """Send prompt to Ollama and return generated text."""
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3,
            "top_p": 0.9,
            "num_predict": 2048,
        },
    }

    resp = requests.post(OLLAMA_URL, json=payload, timeout=600)
    resp.raise_for_status()
    return resp.json()


def extract_json(text):
    """Extract JSON from LLM response, handling thinking tags and code blocks."""
    # Remove <think>...</think> blocks (DeepSeek R1 reasoning)
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)

    # Try to find JSON in code blocks
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0].strip()
    elif "```" in text:
        text = text.split("```")[1].split("```")[0].strip()

    # Try to find JSON object directly
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        text = match.group(0)

    return json.loads(text)


def evaluate_report(report, model):
    """Send one report to the evaluation model."""
    prompt = build_eval_prompt(report)

    response = call_ollama(prompt, model)
    raw_text = response.get("response", "").strip()
    tokens = response.get("eval_count", 0)
    prompt_tokens = response.get("prompt_eval_count", 0)

    evaluation = extract_json(raw_text)

    return {
        "patient_id": report["patient_id"],
        "patient_name": report["patient_name"],
        "scan_date": report["scan_date"],
        "modality": report["modality"],
        "body_site": report["body_site"],
        "ground_truth": report["generation_metadata"]["ground_truth_disease"],
        "generation_model": report["generation_metadata"]["model"],
        "evaluation_model": model,
        "scores": {
            "clinical_accuracy": evaluation["clinical_accuracy"]["score"],
            "no_diagnosis_leakage": evaluation["no_diagnosis_leakage"]["score"],
            "completeness": evaluation["completeness"]["score"],
            "internal_consistency": evaluation["internal_consistency"]["score"],
            "report_quality": evaluation["report_quality"]["score"],
            "overall": evaluation["overall_score"],
        },
        "details": evaluation,
        "evaluated_at": datetime.now().isoformat(),
        "input_tokens": prompt_tokens,
        "output_tokens": tokens,
    }


def print_summary(evaluations):
    """Print summary statistics."""
    if not evaluations:
        return

    criteria = [
        "clinical_accuracy", "no_diagnosis_leakage",
        "completeness", "internal_consistency", "report_quality", "overall",
    ]

    print(f"\n{'='*80}")
    print(f"EVALUATION SUMMARY — {len(evaluations)} reports")
    print(f"Generator: {evaluations[0]['generation_model']}")
    print(f"Evaluator: {evaluations[0]['evaluation_model']}")
    print(f"{'='*80}")

    # Per-criterion averages
    print(f"\n{'Criterion':<25} {'Avg':>6} {'Min':>6} {'Max':>6}")
    print(f"{'─'*50}")
    for c in criteria:
        scores = [e["scores"][c] for e in evaluations]
        avg = sum(scores) / len(scores)
        print(f"{c:<25} {avg:>6.1f} {min(scores):>6.1f} {max(scores):>6.1f}")

    # Per-report breakdown
    print(f"\n{'─'*80}")
    print(f"{'Patient':<25} {'Modality':<12} {'Disease':<30} {'Score':>6}")
    print(f"{'─'*80}")
    for e in evaluations:
        disease = e["ground_truth"][:28]
        print(f"{e['patient_name']:<25} {e['modality'][:10]:<12} {disease:<30} {e['scores']['overall']:>6.1f}")

    # Diagnosis leakage check
    leaks = [
        e for e in evaluations
        if e["scores"]["no_diagnosis_leakage"] < 4
    ]
    if leaks:
        print(f"\nDIAGNOSIS LEAKAGE DETECTED in {len(leaks)} report(s):")
        for e in leaks:
            terms = e["details"]["no_diagnosis_leakage"].get("leaked_terms", [])
            print(f"  {e['patient_name']}: {e['ground_truth']} — leaked: {terms}")

    # Could agent diagnose?
    print(f"\nAgent diagnosability:")
    for val in ["yes", "partially", "no"]:
        count = sum(
            1 for e in evaluations
            if e["details"].get("could_agent_diagnose", "").lower().startswith(val)
        )
        if count:
            print(f"  {val}: {count}/{len(evaluations)}")

    # Token usage
    total_input = sum(e["input_tokens"] for e in evaluations)
    total_output = sum(e["output_tokens"] for e in evaluations)
    print(f"\nToken usage: {total_input:,} input + {total_output:,} output (local — no cost)")


def main():
    parser = argparse.ArgumentParser(description="Evaluate radiology reports using LLM-as-Judge")
    parser.add_argument(
        "--file",
        default=str(REPORTS_DIR / "all_reports.json"),
        help="Path to reports JSON file",
    )
    parser.add_argument("--limit", type=int, help="Max reports to evaluate")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Ollama model for evaluation")
    parser.add_argument("--output", default=str(OUTPUT_DIR), help="Output directory")
    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    reports_path = Path(args.file)
    if not reports_path.exists():
        print(f"Reports file not found: {reports_path}")
        print("Run generate_radiology_reports.py first.")
        return

    # Check Ollama is running
    try:
        requests.get("http://localhost:11434/api/tags", timeout=5)
    except requests.exceptions.ConnectionError:
        print("ERROR: Cannot connect to Ollama. Run: ollama serve")
        return

    print(f"Generator model: GPT-o3 120B (via Ollama)")
    print(f"Evaluator model: {args.model} (via Ollama)")
    print(f"Loading reports from {reports_path}...")
    reports = load_reports(reports_path, limit=args.limit)
    print(f"Found {len(reports)} reports to evaluate\n")

    evaluations = []
    for i, report in enumerate(reports):
        print(f"[{i+1}/{len(reports)}] {report['patient_name']}: "
              f"{report['modality']} — {report['generation_metadata']['ground_truth_disease']}")

        try:
            start = time.time()
            evaluation = evaluate_report(report, args.model)
            duration = time.time() - start

            score = evaluation["scores"]["overall"]
            leakage = evaluation["scores"]["no_diagnosis_leakage"]
            print(f"  Overall: {score}/5.0 | Leakage: {leakage}/5 | {duration:.1f}s")

            evaluations.append(evaluation)

        except requests.exceptions.ConnectionError:
            print("  ERROR: Lost connection to Ollama.")
            return
        except json.JSONDecodeError as e:
            print(f"  ERROR: Could not parse response as JSON: {e}")
            continue
        except Exception as e:
            print(f"  ERROR: {e}")
            continue

    # Save results
    if evaluations:
        eval_path = output_dir / "evaluation_results.json"
        eval_path.write_text(json.dumps(evaluations, indent=2))
        print(f"\nResults saved to {eval_path}")

        print_summary(evaluations)


if __name__ == "__main__":
    main()
