"""Synthea table schemas for the data pipeline.

Each table maps to a list of (column_name, sql_type, is_primary_key).
Used by the Bronze layer for type casting and validation,
and available to Silver/Gold layers for reference.
"""

SCHEMAS = {
    "patients": [
        ("Id", "VARCHAR", True),
        ("BIRTHDATE", "DATE", False),
        ("DEATHDATE", "DATE", False),
        ("SSN", "VARCHAR", False),
        ("DRIVERS", "VARCHAR", False),
        ("PASSPORT", "VARCHAR", False),
        ("PREFIX", "VARCHAR", False),
        ("FIRST", "VARCHAR", False),
        ("MIDDLE", "VARCHAR", False),
        ("LAST", "VARCHAR", False),
        ("SUFFIX", "VARCHAR", False),
        ("MAIDEN", "VARCHAR", False),
        ("MARITAL", "VARCHAR", False),
        ("RACE", "VARCHAR", False),
        ("ETHNICITY", "VARCHAR", False),
        ("GENDER", "VARCHAR", False),
        ("BIRTHPLACE", "VARCHAR", False),
        ("ADDRESS", "VARCHAR", False),
        ("CITY", "VARCHAR", False),
        ("STATE", "VARCHAR", False),
        ("COUNTY", "VARCHAR", False),
        ("FIPS", "VARCHAR", False),
        ("ZIP", "VARCHAR", False),
        ("LAT", "DOUBLE", False),
        ("LON", "DOUBLE", False),
        ("HEALTHCARE_EXPENSES", "DOUBLE", False),
        ("HEALTHCARE_COVERAGE", "DOUBLE", False),
        ("INCOME", "DOUBLE", False),
    ],
    "conditions": [
        ("START", "DATE", True),
        ("STOP", "DATE", False),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("SYSTEM", "VARCHAR", False),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
    ],
    "encounters": [
        ("Id", "VARCHAR", True),
        ("START", "TIMESTAMP", False),
        ("STOP", "TIMESTAMP", False),
        ("PATIENT", "VARCHAR", False),
        ("ORGANIZATION", "VARCHAR", False),
        ("PROVIDER", "VARCHAR", False),
        ("PAYER", "VARCHAR", False),
        ("ENCOUNTERCLASS", "VARCHAR", False),
        ("CODE", "VARCHAR", False),
        ("DESCRIPTION", "VARCHAR", False),
        ("BASE_ENCOUNTER_COST", "DOUBLE", False),
        ("TOTAL_CLAIM_COST", "DOUBLE", False),
        ("PAYER_COVERAGE", "DOUBLE", False),
        ("REASONCODE", "VARCHAR", False),
        ("REASONDESCRIPTION", "VARCHAR", False),
    ],
    "observations": [
        ("DATE", "TIMESTAMP", True),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("CATEGORY", "VARCHAR", False),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("VALUE", "VARCHAR", False),
        ("UNITS", "VARCHAR", False),
        ("TYPE", "VARCHAR", False),
    ],
    "medications": [
        ("START", "TIMESTAMP", True),
        ("STOP", "TIMESTAMP", False),
        ("PATIENT", "VARCHAR", True),
        ("PAYER", "VARCHAR", False),
        ("ENCOUNTER", "VARCHAR", True),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("BASE_COST", "DOUBLE", False),
        ("PAYER_COVERAGE", "DOUBLE", False),
        ("DISPENSES", "INTEGER", False),
        ("TOTALCOST", "DOUBLE", False),
        ("REASONCODE", "VARCHAR", False),
        ("REASONDESCRIPTION", "VARCHAR", False),
    ],
    "imaging_studies": [
        ("Id", "VARCHAR", True),
        ("DATE", "TIMESTAMP", False),
        ("PATIENT", "VARCHAR", False),
        ("ENCOUNTER", "VARCHAR", False),
        ("SERIES_UID", "VARCHAR", False),
        ("BODYSITE_CODE", "VARCHAR", False),
        ("BODYSITE_DESCRIPTION", "VARCHAR", False),
        ("MODALITY_CODE", "VARCHAR", False),
        ("MODALITY_DESCRIPTION", "VARCHAR", False),
        ("INSTANCE_UID", "VARCHAR", False),
        ("SOP_CODE", "VARCHAR", False),
        ("SOP_DESCRIPTION", "VARCHAR", False),
        ("PROCEDURE_CODE", "VARCHAR", False),
    ],
    "procedures": [
        ("START", "TIMESTAMP", True),
        ("STOP", "TIMESTAMP", False),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("SYSTEM", "VARCHAR", False),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("BASE_COST", "DOUBLE", False),
        ("REASONCODE", "VARCHAR", False),
        ("REASONDESCRIPTION", "VARCHAR", False),
    ],
    "allergies": [
        ("START", "DATE", True),
        ("STOP", "DATE", False),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("CODE", "VARCHAR", True),
        ("SYSTEM", "VARCHAR", False),
        ("DESCRIPTION", "VARCHAR", False),
        ("TYPE", "VARCHAR", False),
        ("CATEGORY", "VARCHAR", False),
        ("REACTION1", "VARCHAR", False),
        ("DESCRIPTION1", "VARCHAR", False),
        ("SEVERITY1", "VARCHAR", False),
        ("REACTION2", "VARCHAR", False),
        ("DESCRIPTION2", "VARCHAR", False),
        ("SEVERITY2", "VARCHAR", False),
    ],
    "careplans": [
        ("Id", "VARCHAR", True),
        ("START", "DATE", False),
        ("STOP", "DATE", False),
        ("PATIENT", "VARCHAR", False),
        ("ENCOUNTER", "VARCHAR", False),
        ("CODE", "VARCHAR", False),
        ("DESCRIPTION", "VARCHAR", False),
        ("REASONCODE", "VARCHAR", False),
        ("REASONDESCRIPTION", "VARCHAR", False),
    ],
    "claims": [
        ("Id", "VARCHAR", True),
        ("PATIENTID", "VARCHAR", False),
        ("PROVIDERID", "VARCHAR", False),
        ("PRIMARYPATIENTINSURANCEID", "VARCHAR", False),
        ("SECONDARYPATIENTINSURANCEID", "VARCHAR", False),
        ("DEPARTMENTID", "VARCHAR", False),
        ("PATIENTDEPARTMENTID", "VARCHAR", False),
        ("DIAGNOSIS1", "VARCHAR", False),
        ("DIAGNOSIS2", "VARCHAR", False),
        ("DIAGNOSIS3", "VARCHAR", False),
        ("DIAGNOSIS4", "VARCHAR", False),
        ("DIAGNOSIS5", "VARCHAR", False),
        ("DIAGNOSIS6", "VARCHAR", False),
        ("DIAGNOSIS7", "VARCHAR", False),
        ("DIAGNOSIS8", "VARCHAR", False),
        ("REFERRINGPROVIDERID", "VARCHAR", False),
        ("APPOINTMENTID", "VARCHAR", False),
        ("CURRENTILLNESSDATE", "DATE", False),
        ("SERVICEDATE", "DATE", False),
        ("SUPERVISINGPROVIDERID", "VARCHAR", False),
        ("STATUS1", "VARCHAR", False),
        ("STATUS2", "VARCHAR", False),
        ("STATUSP", "VARCHAR", False),
        ("OUTSTANDING1", "DOUBLE", False),
        ("OUTSTANDING2", "DOUBLE", False),
        ("OUTSTANDINGP", "DOUBLE", False),
        ("LASTBILLEDDATE1", "DATE", False),
        ("LASTBILLEDDATE2", "DATE", False),
        ("LASTBILLEDDATEP", "DATE", False),
        ("HEALTHCARECLAIMTYPEID1", "VARCHAR", False),
        ("HEALTHCARECLAIMTYPEID2", "VARCHAR", False),
    ],
    "claims_transactions": [
        ("ID", "VARCHAR", True),
        ("CLAIMID", "VARCHAR", True),
        ("CHARGEID", "VARCHAR", False),
        ("PATIENTID", "VARCHAR", False),
        ("TYPE", "VARCHAR", False),
        ("AMOUNT", "DOUBLE", False),
        ("METHOD", "VARCHAR", False),
        ("FROMDATE", "DATE", False),
        ("TODATE", "DATE", False),
        ("PLACEOFSERVICE", "VARCHAR", False),
        ("PROCEDURECODE", "VARCHAR", False),
        ("MODIFIER1", "VARCHAR", False),
        ("MODIFIER2", "VARCHAR", False),
        ("DIAGNOSISREF1", "VARCHAR", False),
        ("DIAGNOSISREF2", "VARCHAR", False),
        ("DIAGNOSISREF3", "VARCHAR", False),
        ("DIAGNOSISREF4", "VARCHAR", False),
        ("UNITS", "VARCHAR", False),
        ("DEPARTMENTID", "VARCHAR", False),
        ("NOTES", "VARCHAR", False),
        ("UNITAMOUNT", "DOUBLE", False),
        ("TRANSFEROUTID", "VARCHAR", False),
        ("TRANSFERTYPE", "VARCHAR", False),
        ("PAYMENTS", "DOUBLE", False),
        ("ADJUSTMENTS", "DOUBLE", False),
        ("TRANSFERS", "DOUBLE", False),
        ("OUTSTANDING", "DOUBLE", False),
        ("APPOINTMENTID", "VARCHAR", False),
        ("LINENOTE", "VARCHAR", False),
        ("PATIENTINSURANCEID", "VARCHAR", False),
        ("FEESCHEDULEID", "VARCHAR", False),
        ("PROVIDERID", "VARCHAR", False),
        ("SUPERVISINGPROVIDERID", "VARCHAR", False),
    ],
    "devices": [
        ("START", "TIMESTAMP", True),
        ("STOP", "TIMESTAMP", False),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("UDI", "VARCHAR", False),
    ],
    "immunizations": [
        ("DATE", "TIMESTAMP", True),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("BASE_COST", "DOUBLE", False),
    ],
    "payer_transitions": [
        ("PATIENT", "VARCHAR", True),
        ("MEMBERID", "VARCHAR", False),
        ("START_DATE", "DATE", False),
        ("END_DATE", "DATE", False),
        ("PAYER", "VARCHAR", False),
        ("SECONDARY_PAYER", "VARCHAR", False),
        ("PLAN_OWNERSHIP", "VARCHAR", False),
        ("OWNER_NAME", "VARCHAR", False),
    ],
    "supplies": [
        ("DATE", "DATE", True),
        ("PATIENT", "VARCHAR", True),
        ("ENCOUNTER", "VARCHAR", True),
        ("CODE", "VARCHAR", True),
        ("DESCRIPTION", "VARCHAR", False),
        ("QUANTITY", "INTEGER", False),
    ],
}


def get_columns(table_name):
    """Get column names for a table."""
    return [col for col, _, _ in SCHEMAS[table_name]]


def get_pk_columns(table_name):
    """Get primary key columns for a table."""
    return [col for col, _, is_pk in SCHEMAS[table_name] if is_pk]


def get_column_type(table_name, column_name):
    """Get the SQL type for a specific column."""
    for col, col_type, _ in SCHEMAS[table_name]:
        if col == column_name:
            return col_type
    return None


def build_cast_select(table_name):
    """Build a SELECT with TRY_CAST for each column to its target type."""
    cols = []
    for col_name, col_type, _ in SCHEMAS[table_name]:
        if col_type == "VARCHAR":
            cols.append(f'"{col_name}"')
        else:
            cols.append(f'TRY_CAST("{col_name}" AS {col_type}) AS "{col_name}"')
    return ", ".join(cols)
